#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: client-id
#            client-secret: client-secret
#
#logging:
#  level:
#    org.springframework.security: TRACE
